import type { QuickSettingsStyle } from '../stores/types'
import type { QuickSettingsMode } from './quick-settings'
import { findFirstDeclarationValue, parseCssTopLevelBlocks } from '../../../lib/css-ast'

/**
 * Shared CSS <-> quick-start-state round-tripping.
 *
 * Two distinct cases exist:
 * - Reading a preset's own shipped `quick-start.css` to seed editor defaults for that theme.
 *   That CSS is hand-authored once at build time and never carries markers, so this always
 *   falls back to the literal-value heuristics below.
 * - Re-deriving state from CSS the editor itself previously generated (hand-edited in the
 *   CodeMirror editor, or re-imported from a previously-exported JAR). CSS generated by
 *   `buildQuickStartCssParts` (see quick-start-css.ts) emits a `@kte:<key>=<value>` marker
 *   comment next to every enum-valued token, so this case can round-trip exactly instead of
 *   guessing from the literal CSS value — the literal-value heuristics only apply here when
 *   the markers have been stripped (e.g. exports produced before this change).
 */

export type QuickStartMarkerKey = 'border-radius' | 'card-shadow'

export function buildQuickStartMarkerComment(key: QuickStartMarkerKey, value: string): string {
  return `/* @kte:${key}=${value} */`
}

function parseQuickStartMarkerValue(cssText: string, key: QuickStartMarkerKey): string | null {
  const match = cssText.match(new RegExp(`/\\*\\s*@kte:${key}=([a-zA-Z0-9_-]+)\\s*\\*/`))
  return match?.[1] ?? null
}

export function classifyModeBySelector(selectorText: string): QuickSettingsMode | 'shared' {
  const selector = selectorText.toLowerCase()
  if (selector.includes(':not(.pf-v5-theme-dark)') || selector.includes(':not(.kcdarkmodeclass)')) {
    return 'light'
  }
  if (
    selector.includes('html.pf-v5-theme-dark')
    || selector.includes('body.pf-v5-theme-dark')
    || selector.includes('html.kcdarkmodeclass')
    || selector.includes('body.kcdarkmodeclass')
  ) {
    return 'dark'
  }
  return 'shared'
}

/**
 * Raw CSS text for rule blocks scoped to `mode` or shared - used to resolve `@kte:` marker
 * comments (e.g. `border-radius`/`card-shadow`) for the right mode. Unlike a declaration-value
 * lookup, markers live in comments rather than declarations, so a selector-scoped raw-text search
 * is needed instead - otherwise a light-mode marker could be picked up while parsing dark mode
 * (or vice versa) when both are concatenated in the same CSS file.
 */
export function extractQuickStartCssForMode(cssText: string, mode: QuickSettingsMode): string {
  const raw: string[] = []

  const collectRule = (selector: string, ruleRaw: string) => {
    const ruleMode = classifyModeBySelector(selector)
    if (ruleMode === 'shared' || ruleMode === mode) {
      raw.push(ruleRaw)
    }
  }

  for (const block of parseCssTopLevelBlocks(cssText)) {
    if (block.type === 'rule') {
      collectRule(block.selector, block.raw)
    }
    else if (block.type === 'media') {
      for (const innerRule of block.innerRules) {
        collectRule(innerRule.selector, innerRule.raw)
      }
    }
  }

  return raw.join('\n')
}

export function readQuickStartVariable(cssText: string, variableName: string): string {
  return findFirstDeclarationValue(cssText, variableName)
}

export function normalizeEditableQuickStartValue(value: string): string {
  const normalized = value.trim()
  return normalized.startsWith('var(') ? '' : normalized
}

/** Reads a mode-aware quickstart color variable by scanning raw CSS text (not selector-scoped). */
export function readQuickStartColorVariable(
  cssText: string,
  suffix: 'primary-color' | 'secondary-color' | 'bg-color',
  mode: 'light' | 'dark',
): string {
  const candidates = mode === 'dark'
    ? [`--quickstart-${suffix}-dark`, `--quickstart-${suffix}-light`]
    : [`--quickstart-${suffix}-light`, `--quickstart-${suffix}-dark`]

  for (const candidate of candidates) {
    const value = normalizeEditableQuickStartValue(readQuickStartVariable(cssText, candidate))
    if (value) {
      return value
    }
  }

  return ''
}

/**
 * Maps a resolved `--quickstart-border-radius` CSS value back to its enum. Prefers the exact
 * `@kte:border-radius=...` marker comment; falls back to literal-value matching when no marker
 * is present.
 */
export function mapQuickStartBorderRadius(cssText: string, value: string): QuickSettingsStyle['colorPresetBorderRadius'] {
  const marker = parseQuickStartMarkerValue(cssText, 'border-radius')
  if (marker === 'sharp' || marker === 'rounded' || marker === 'pill') {
    return marker
  }

  const normalized = value.trim().toLowerCase()
  if (normalized === '0' || normalized === '0px') {
    return 'sharp'
  }
  if (normalized === '24px') {
    return 'pill'
  }
  return 'rounded'
}

/**
 * Maps a resolved `--quickstart-card-shadow` CSS value back to its enum. Prefers the exact
 * `@kte:card-shadow=...` marker comment; falls back to literal-value matching when no marker
 * is present.
 */
export function mapQuickStartCardShadow(cssText: string, value: string): QuickSettingsStyle['colorPresetCardShadow'] {
  const marker = parseQuickStartMarkerValue(cssText, 'card-shadow')
  if (marker === 'none' || marker === 'subtle' || marker === 'strong') {
    return marker
  }

  const normalized = value.trim().toLowerCase().replace(/\s+/g, ' ')
  if (!normalized) {
    return 'subtle'
  }
  if (normalized === 'none') {
    return 'none'
  }
  if (normalized.includes('0 8px 32px')) {
    return 'strong'
  }
  return 'subtle'
}
