/**
 * The class-hook vocabulary exposed by our `base` variant.
 *
 * Unlike `v2`, this is NOT derived from a single pristine upstream file: real
 * Keycloak's `base` theme is `abstract=true` and declares no concrete class
 * hooks at all (only `locales=`). This list only ever grows when *we* add a new
 * CSS hook to our own templates/CSS - a Keycloak version bump does not change
 * it. That is a deliberate authoring decision, not vendored content, which is
 * why it lives here as data instead of being regenerated from a sync.
 *
 * Bootstrapped from the committed `base/login/theme.properties` on 2026-08-23
 * (Keycloak 26.6.4) so the golden test in `theme-adaptations.test.ts` proves
 * byte-identical reproduction before this file is trusted for anything else.
 */
export const BASE_CLASS_HOOK_KEYS: readonly string[] = [
  'kcAlertClass',
  'kcAlertDescriptionClass',
  'kcAlertIconClass',
  'kcAlertTitleClass',
  'kcAngleDownIconClass',
  'kcAngleRightIconClass',
  'kcAuthenticatorDefaultClass',
  'kcAuthenticatorOTPClass',
  'kcAuthenticatorPasswordClass',
  'kcAuthenticatorRecoveryAuthnCodesClass',
  'kcAuthenticatorWebAuthnClass',
  'kcAuthenticatorWebAuthnPasswordlessClass',
  'kcBodyClass',
  'kcButtonBlockClass',
  'kcButtonClass',
  'kcButtonLargeClass',
  'kcButtonLinkClass',
  'kcButtonPrimaryClass',
  'kcButtonSecondaryClass',
  'kcCheckboxClass',
  'kcCheckboxInputClass',
  'kcCheckboxLabelClass',
  'kcCheckboxLabelRequiredClass',
  'kcCheckIconClass',
  'kcCodeClipboardCopyClass',
  'kcCodeClipboardCopyContentClass',
  'kcCodeClipboardCopyGroupClass',
  'kcCommonLogoIdP',
  'kcContentWrapperClass',
  'kcCopyIconClass',
  'kcDarkModeClass',
  'kcError',
  'kcExpandedClass',
  'kcFeedbackErrorIcon',
  'kcFeedbackInfoIcon',
  'kcFeedbackSuccessIcon',
  'kcFeedbackWarningIcon',
  'kcFill',
  'kcFormActionGroupClass',
  'kcFormCardClass',
  'kcFormClass',
  'kcFormControlToggleIcon',
  'kcFormControlUtilClass',
  'kcFormGroupClass',
  'kcFormGroupLabelClass',
  'kcFormHeaderClass',
  'kcFormHelperTextClass',
  'kcFormLabelClass',
  'kcFormLabelTextClass',
  'kcFormOptionsWrapperClass',
  'kcFormPasswordVisibilityButtonClass',
  'kcFormPasswordVisibilityIconHide',
  'kcFormPasswordVisibilityIconShow',
  'kcFormReadOnlyClass',
  'kcFormSettingClass',
  'kcFormSocialAccountGridItem',
  'kcFormSocialAccountListButtonClass',
  'kcFormSocialAccountListButtonDisabledClass',
  'kcFormSocialAccountListClass',
  'kcFormSocialAccountListGridClass',
  'kcFormSocialAccountListItemClass',
  'kcFormSocialAccountNameClass',
  'kcFormSocialAccountSectionClass',
  'kcHeaderClass',
  'kcHeaderWrapperClass',
  'kcHtmlClass',
  'kcInfoAreaWrapperClass',
  'kcInputClass',
  'kcInputErrorIconClass',
  'kcInputErrorIconStatusClass',
  'kcInputErrorMessageClass',
  'kcInputGroup',
  'kcInputGroupItemClass',
  'kcInputHelperTextClass',
  'kcInputHelperTextItemClass',
  'kcInputHelperTextItemTextClass',
  'kcInputRequiredClass',
  'kcLabelClass',
  'kcLabelWrapperClass',
  'kcListClass',
  'kcLocaleDropDownClass',
  'kcLocaleItemClass',
  'kcLocaleListClass',
  'kcLocaleListItemClass',
  'kcLocaleMainClass',
  'kcLocaleWrapperClass',
  'kcLogin',
  'kcLoginClass',
  'kcLoginContainer',
  'kcLoginFooterBand',
  'kcLoginFooterBandItem',
  'kcLoginMain',
  'kcLoginMainBody',
  'kcLoginMainFooter',
  'kcLoginMainFooterBand',
  'kcLoginMainFooterBandItem',
  'kcLoginMainFooterHelperText',
  'kcLoginMainHeader',
  'kcLoginMainHeaderUtilities',
  'kcLoginMainTitle',
  'kcLoginOTPListClass',
  'kcLoginOTPListItemHeaderClass',
  'kcLoginOTPListItemIconBodyClass',
  'kcLoginOTPListItemIconClass',
  'kcLoginOTPListItemTitleClass',
  'kcLoginOTPListSelectedClass',
  'kcLogoIdP-bitbucket',
  'kcLogoIdP-facebook',
  'kcLogoIdP-github',
  'kcLogoIdP-gitlab',
  'kcLogoIdP-google',
  'kcLogoIdP-instagram',
  'kcLogoIdP-linkedin',
  'kcLogoIdP-microsoft',
  'kcLogoIdP-openshift-v4',
  'kcLogoIdP-paypal',
  'kcLogoIdP-stackoverflow',
  'kcLogoIdP-twitter',
  'kcMarginTopClass',
  'kcPanelClass',
  'kcPanelMainBodyClass',
  'kcPanelMainClass',
  'kcRecoveryCodesWarning',
  'kcResetFlowIcon',
  'kcSelectAuthListClass',
  'kcSelectAuthListItemArrowIconClass',
  'kcSelectAuthListItemBodyClass',
  'kcSelectAuthListItemClass',
  'kcSelectAuthListItemDescriptionClass',
  'kcSelectAuthListItemFillClass',
  'kcSelectAuthListItemHeadingClass',
  'kcSelectAuthListItemIconClass',
  'kcSelectAuthListItemWrapperClass',
  'kcSignUpClass',
  'kcWebAuthnDefaultIcon',
]

/**
 * The one key that isn't a bare self-reference: dark mode must still add a
 * real, functional PatternFly class or toggling dark mode would do nothing.
 */
export const BASE_CLASS_HOOK_OVERRIDES: Readonly<Record<string, string>> = {
  kcDarkModeClass: 'pf-v5-theme-dark',
}
