import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { compile } from 'sass'

const bindingDirectory = resolve('src/features/editor/lib/framework-bindings')
const bulmaDirectory = resolve('node_modules/bulma')
const interDirectory = resolve('node_modules/@fontsource/inter')

const bulmaVersion = (JSON.parse(readFileSync(resolve(bulmaDirectory, 'package.json'), 'utf8')) as { version: string }).version
const bulmaLicense = readFileSync(resolve(bulmaDirectory, 'LICENSE'), 'utf8').trim()
const interLicense = readFileSync(resolve(interDirectory, 'LICENSE'), 'utf8').trim()

// Embed fonts so both srcdoc previews and exported JARs work without a CDN or asset rewriting.
const subsetRanges = {
  'latin': 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  'latin-ext': 'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
}
// Only the weights the login pages actually render: Bulma uses semibold once, the token bridge
// uses medium, and nothing in Keycloak's markup is bold.
const fonts = [400, 500, 600].flatMap(weight =>
  Object.entries(subsetRanges).map(([subset, unicodeRange]) => {
    const data = readFileSync(resolve(interDirectory, `files/inter-${subset}-${weight}-normal.woff2`)).toString('base64')
    return `@font-face{font-family:"Inter";font-style:normal;font-weight:${weight};font-display:swap;unicode-range:${unicodeRange};src:url("data:font/woff2;base64,${data}") format("woff2")}`
  }),
).join('\n')

const { css } = compile(resolve(bindingDirectory, 'bulma.scss'), {
  loadPaths: [resolve('node_modules')],
  style: 'compressed',
  quietDeps: true,
})

writeFileSync(resolve(bindingDirectory, 'bulma.generated.css'), [
  `/*! Generated by npm run generate:bulma. Bulma v${bulmaVersion}: https://bulma.io */`,
  `/*! Bulma license:\n${bulmaLicense}\n*/`,
  `/*! Inter font license:\n${interLicense}\n*/`,
  fonts,
  css.replace(/^@charset "UTF-8";\s*/, ''),
  '',
].join('\n'))
