import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { compile } from 'sass'

// Embed fonts so both srcdoc previews and exported JARs work without a CDN or asset rewriting.
const bindingDirectory = resolve('src/features/editor/lib/framework-bindings')
const plexDirectory = resolve('node_modules/@ibm/plex/IBM-Plex-Sans/fonts/complete/woff2')
const fontLicense = readFileSync(resolve(plexDirectory, 'license.txt'), 'utf8')
const carbonLicense = readFileSync(resolve('node_modules/@carbon/styles/LICENSE'), 'utf8')
const fonts = [['Regular', 400], ['Medium', 500], ['SemiBold', 600]].map(([name, weight]) => {
  const data = readFileSync(resolve(plexDirectory, `IBMPlexSans-${name}.woff2`)).toString('base64')
  return `@font-face{font-family:"IBM Plex Sans";font-style:normal;font-weight:${weight};font-display:swap;src:url("data:font/woff2;base64,${data}") format("woff2")}`
}).join('\n')
const { css } = compile(resolve(bindingDirectory, 'carbon.scss'), {
  loadPaths: [resolve('node_modules')],
  style: 'compressed',
  quietDeps: true,
})
writeFileSync(resolve(bindingDirectory, 'carbon.generated.css'), [
  '/*! Generated by npm run generate:carbon. Carbon styles: Copyright IBM Corp., Apache-2.0. */',
  `/*! Carbon license:\n${carbonLicense}\n*/`,
  `/*! IBM Plex font license:\n${fontLicense}\n*/`,
  fonts,
  css,
  '',
].join('\n'))
